# Generated by Django 5.0.7 on 2024-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_places_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Coordinates',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
